name: ci
on: pull_request

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2      
                        
      - name: Build image
        run: "make python-all -e VERSION=${{ github.sha }}"
        
          
