name: ci
on: pull_request

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.1.0
        
      - name: Install dependencies
        run: poetry install

      - name: Test code
        run: poetry run pytest test

      - name: Build image
        run: make python-all -e VERSION=${{ github.sha }}
 
