name: ci
on: pull_request

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2      
                        
      - name: Build image
        run: "make python-all -e VERSION=${{ github.sha }}"
        
      - name: Get list images 
        run: |
          IMAGE=$(docker images | grep serving-runtime | awk '{print $3}')
          echo $IMAGE

      - name: Inspect images
        run: |
          for i in $IMAGE
          do
            docker image inspect $i
          done  
