name: ci
on: pull_request

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2      
                        
      - name: Build image
        run: "make python-all -e VERSION=${{ github.sha }}"
        
      - name: Get list images 
        id: get-images
        run: |
          IMAGE=$(docker images | grep serving-runtime | awk '{print $3}')
          echo $IMAGE
          echo "IMAGES=$IMAGE" >> $GITHUB_ENV
      

      - name: Inspect images
        run: |
          echo ${{ env.IMAGES }}
          for i in ${{ env.IMAGES }}
          do
            docker image inspect $i
          done  
