name: ci
on: pull_request

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.1.0
        
      - name: Install dependencies
        run: poetry install

      - name: bump version
        run: poetry version prerelease

      - name: Test code
        run: poetry run pytest test

      - name: Build image
        run: make python-all -e VERSION=${{ github.sha }}
 
 